name: Coveralls
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      BIT_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies and run Tests
        run: |
             ls -la
             sudo apt-get install cmake libgtest-dev libgmock-dev gcovr
             ls -la 
             chmod 775 start_testing.sh
             ./start_testing.sh

 
