name: Coveralls
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies and run Tests
        run: |
             ls -la
             sudo apt-get install cmake libgtest-dev libgmock-dev gcovr
             ls -la 
             chmod 775 start_testing.sh
             ./start_testing.sh
             sudo rm /usr/lib/python3.12/EXTERNALLY-MANAGED
             pip3 install coveralls   
      
      - name: Generate coverage report
      - uses: threeal/gcovr-action@v1.0.0
        with:
          excludes: |
            src/*
          gcov-executable: llvm-cov gcov
          xml-out: coverage.xml
          coveralls-out: coverage.json
          coveralls-send: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Send coverage data to Coveralls
        uses: coverallsapp/github-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: coverage.json
 
